#!/bin/sh
#
# Copyright (c) 2014 Amlogic, Inc. All rights reserved.
# This source code is subject to the terms and conditions defined in the file 'LICENSE' which is part of this source code package.
# Description: start|stop|resetart the dspb
#


case "$1" in
  start)
    # load firmware
    if [ -f /lib/firmware/dspbootB_sram.bin ]; then
        dsp_util --load2 --dsp hifi4b --firmware1 dspbootB_sdram.bin --firmware2 dspbootB_sram.bin
    else
        dsp_util --load --dsp hifi4b -f dspbootB.bin
    fi
    # Launch DSP rtos
    dsp_util -S --dsp hifi4b
    ;;
  stop)
    echo -n "Do thing: "
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
