#!/bin/sh
#
# Copyright (c) 2023 Amlogic, Inc. All rights reserved.
# This source code is subject to the terms and conditions defined
# in the file 'LICENSE' which is part of this source code package.
# Description:  Run the mdev daemon
#

DAEMON="mdev"
PIDFILE="/var/run/$DAEMON.pid"


start() {
	echo -n "Starting $DAEMON... "
	start-stop-daemon -S -b -m -p $PIDFILE -x /sbin/mdev -- -df
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

stop() {
	echo -n "Stopping $DAEMON... "
	start-stop-daemon -K -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
