#!/bin/sh
#
# Copyright (c) 2023 Amlogic, Inc. All rights reserved.
# This source code is subject to the terms and conditions defined
# in the file 'LICENSE' which is part of this source code package.
# Description:  modules load
#

load_modules()
{
    #usb modules
    insmod /amlogic/modules/vendor/amlogic-usb.ko
    insmod /amlogic/modules/vendor/dwc3.ko
    insmod /amlogic/modules/vendor/dwc3-of-simple.ko
    insmod /amlogic/modules/vendor/xhci-plat-hcd.ko
    insmod /amlogic/modules/vendor/dwc_otg.ko
    #wifi/bt modules
    insmod /amlogic/modules/vendor/amlogic-mmc.ko
    insmod /amlogic/modules/vendor/amlogic-wireless.ko
}

case "$1" in
  start)
	  load_modules
		;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?

