#!/bin/sh
#
# aml pq service
#

PID_FILE=/tmp/aml_pq_service.pid

DAEMON=pqservice
DAEMON_ARGS=""
export PQ_CONFIG_FILE_PATH=/vendor/etc/tvconfig/pq/pq_default.ini

start() {
  if [ -f $PID_FILE ] && kill -0 $(cat $PID_FILE); then
    echo "$DAEMON already running"
    return 1
  fi
  printf "Starting AML PQ Server..."
  eval "$DAEMON $DAEMON_ARGS &"
  echo $! > $PID_FILE
}

stop() {
  if [ ! -f "$PID_FILE" ] || ! kill -0 $(cat "$PID_FILE"); then
    echo "$DAEMON not running"
    return 1
  fi
  printf "Stopping $DAEMON "
  kill $(cat $PID_FILE) && rm -f $PID_FILE
  echo "$DAEMON stopped"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
