################################################################################
#
# webkitbrowser-plugin
#
################################################################################

WEBKITBROWSER_PLUGIN_VERSION = 6ae314d5c6b7f81e5a2df0b55bd8414554b50b80
WEBKITBROWSER_PLUGIN_SITE_METHOD = git
WEBKITBROWSER_PLUGIN_SITE = git://github.com/rdkcentral/rdkservices.git
#WPEFRAMEWORK_RDKSERVICES_INSTALL_STAGING = YES
WEBKITBROWSER_PLUGIN_DEPENDENCIES = wpeframework  wpewebkit


WEBKITBROWSER_PLUGIN_EXTRA_FLAGS = \
	-DCMAKE_CXX_FLAGS="-O3 $(TARGET_CXXFLAGS) -O2  -I$(STAGING_DIR)/usr/include/wdmp-c  -I$(STAGING_DIR)/usr/include/rdk/iarmbus  -I$(STAGING_DIR)/usr/include/trower-base64 -std=c++11 -fexceptions  -fexceptions -Wno-cast-align"  \
	-DCOMPILE_FLAGS="-std=c++11 -fexceptions -fexceptions -Wno-cast-align"





# ----------------------------------------------------------------------------

WEBKITBROWSER_PLUGIN_CONF_OPTS  =  -DCMAKE_BUILD_TYPE=Debug,-DCMAKE_BUILD_TYPE=Release, \
		-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=ON,-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=OFF,\
		-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=ON,-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=OFF,\
		-DPLUGIN_WEBKITBROWSER_HTML_APP=ON,-DPLUGIN_WEBKITBROWSER_HTML_APP=OFF,\
		-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=ON,-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=OFF,\
		-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=ON,-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=OFF,aamp \
		-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=ON,-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=OFF



WEBKITBROWSER_AUTOSTART ?= "false"
WEBKITBROWSER_MEDIADISKCACHE ?= "false"
WEBKITBROWSER_MEMORYPRESSURE ?= "databaseprocess:50m,networkprocess:50m,webprocess:200m,rpcprocess:50m"
WEBKITBROWSER_MEMORYPROFILE ?= "192m"
WEBKITBROWSER_MSEBUFFERS ?= "audio:2m,video:15m,text:1m"
WEBKITBROWSER_STARTURL ?= "about:blank"
WEBKITBROWSER_DISKCACHE ?= "10"
WEBKITBROWSER_XHRCACHE ?= "false"
WEBKITBROWSER_TRANSPARENT ?= "true"
WEBKITBROWSER_INJECTEBLE_BUNDLE ?= "libWPEInjectedBundle.so"


WEBKITBROWSER_PLUGIN_CONF_OPTS +=     -DPYTHON_EXECUTABLE=$(@HOST_DIR)/bin/python3 \
    -DCMAKE_SYSROOT=$(@D)
    -DBUILD_REFERENCE=$(@D) \
    -DBUILD_SHARED_LIBS=ON \
    -DPLUGIN_WEBKITBROWSER=ON \
    -DPLUGIN_WEBKITBROWSER_AUTOSTART=$(WEBKITBROWSER_AUTOSTART) \
    -DPLUGIN_WEBKITBROWSER_MEDIADISKCACHE=$(WEBKITBROWSER_MEDIADISKCACHE) \
    -DPLUGIN_WEBKITBROWSER_MEMORYPRESSURE=$(WEBKITBROWSER_MEMORYPRESSURE) \
    -DPLUGIN_WEBKITBROWSER_MEMORYPROFILE=$(WEBKITBROWSER_MEMORYPROFILE) \
    -DPLUGIN_WEBKITBROWSER_MSEBUFFERS=$(WEBKITBROWSER_MSEBUFFERS)  \
    -DPLUGIN_WEBKITBROWSER_STARTURL=$(WEBKITBROWSER_STARTURL) \
    -DPLUGIN_WEBKITBROWSER_DISKCACHE=$(WEBKITBROWSER_DISKCACHE) \
    -DPLUGIN_WEBKITBROWSER_XHRCACHE=$(WEBKITBROWSER_XHRCACHE) \
    -DPLUGIN_WEBKITBROWSER_TRANSPARENT=$(WEBKITBROWSER_TRANSPARENT) \
    -DPLUGIN_WEBKITBROWSER_INJECTEBLE_BUNDLE=$(WEBKITBROWSER_INJECTEBLE_BUNDLE)




RESIDENT_APP_CLIENTIDENTIFIER ?= wst-residentapp
SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER ?= wst-searchanddiscoveryapp
WEBKITBROWSER_CLIENTIDENTIFIER ?= wst-webkitbrowser
HTML_APP_CLIENTIDENTIFIER ?= wst-htmlapp
LIGHTNING_APP_CLIENTIDENTIFIER ?= wst-lightningapp
RESIDENT_APP_AUTOSTART ?= "true"
RESIDENT_APP_STARTURL ?= "http://localhost:50050/dist/edge/index.html"

WEBKITBROWSER_DISKCACHEDIR = "/tmp/data/.cache/wpe/disk-cache"
HTML_APP_LOCALSTORAGE = "/opt/persistent/rdkservices/HtmlApp"
LIGHTNING_APP_LOCALSTORAGE = "/opt/persistent/rdkservices/LightningApp"
SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE = "/opt/persistent/rdkservices/SearchAndDiscoveryApp"
RESIDENT_APP_LOCALSTORAGE = "/opt/persistent/rdkservices/ResidentApp"



WEBKITBROWSER_PLUGIN_CONF_OPTS +=
 -DPLUGIN_RESIDENT_APP_CLIENTIDENTIFIER=$(RESIDENT_APP_CLIENTIDENTIFIER) \
 -DPLUGIN_RESIDENT_APP_AUTOSTART=$(RESIDENT_APP_AUTOSTART) \
 -DPLUGIN_RESIDENT_APP_STARTURL=$(RESIDENT_APP_STARTURL) \
 -DPLUGIN_SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER=$(SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER) \
 -DPLUGIN_WEBKITBROWSER_CLIENTIDENTIFIER=$(WEBKITBROWSER_CLIENTIDENTIFIER) \
 -DPLUGIN_HTML_APP_CLIENTIDENTIFIER=$(HTML_APP_CLIENTIDENTIFIER) \
 -DPLUGIN_LIGHTNING_APP_CLIENTIDENTIFIER=$(LIGHTNING_APP_CLIENTIDENTIFIER) \
 -DPLUGIN_WEBKITBROWSER_DISKCACHEDIR=$(WEBKITBROWSER_DISKCACHEDIR) \
 -DPLUGIN_HTML_APP_LOCALSTORAGE=$(HTML_APP_LOCALSTORAGE) \
 -DPLUGIN_HTML_APP_COOKIESTORAGE=$(HTML_APP_LOCALSTORAGE) \
 -DPLUGIN_LIGHTNING_APP_LOCALSTORAGE=$(LIGHTNING_APP_LOCALSTORAGE) \
 -DPLUGIN_LIGHTNING_APP_COOKIESTORAGE=$(LIGHTNING_APP_LOCALSTORAGE) \
 -DPLUGIN_SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE=$(SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE) \
 -DPLUGIN_SEARCH_AND_DISCOVERY_APP_COOKIESTORAGE=$(SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE) \
 -DPLUGIN_RESIDENT_APP_LOCALSTORAGE=$(RESIDENT_APP_LOCALSTORAGE) \
 -DPLUGIN_RESIDENT_APP_COOKIESTORAGE=$(RESIDENT_APP_LOCALSTORAGE) \




WEBKITBROWSER_CLIENT_CERT=/etc/rdkbrowser2/ottapps.xcal.tv.cert.pem
WEBKITBROWSER_CLIENT_CERT_KEY=/tmp/.rdkbrowser2_init/.yreguglpgpmd.socket

WEBKITBROWSER_PLUGIN_CONF_OPTS += \
  -DPLUGIN_WEBKITBROWSER_CLIENT_CERT=$(WEBKITBROWSER_CLIENT_CERT) \
  -DPLUGIN_WEBKITBROWSER_CLIENT_CERT_KEY=$(WEBKITBROWSER_CLIENT_CERT_KEY)



WEBKITBROWSER_PLUGIN_CONF_OPTS  +=   \
	-DPLUGIN_CONTROLSERVICE=OFF \
	-DHAS_API_CONTINUE_WATCHING=OFF
	-DCONTINUEWATCHING_DISABLE_SECAPI=OFF\ 
	DSECAPI_LIB=OFF \
    -DCONTINUEWATCHING_DISABLE_SECAPI=OFF \
    -DPLUGIN_REMOTEACTIONMAPPING=OFF \
    -DPLUGIN_CONTROLSERVICE=OFF \
    -DPLUGIN_VREXMANAGER=OFF \
    -DENABLE_SECURITY_AGENT=OFF \
    -DHAS_API_HDMI_CEC=OFF \
    -DENABLE_OPEN_CDMI=OFF \
   -DPLUGIN_OPENCDMI_AUTOSTART=false \
   -DPLUGIN_OPENCDMI_OOP=OFF   \
   -DPLUGIN_DISPLAYSETTINGS=OFF \
    -DWAREHOUSE_API=OFF \
    -DBUILD_ENABLE_HDCP=OFF \
    -DHAS_API_HDMI_INPUT=OFF -DUSE_DS=NO -DCLOCK_BRIGHTNESS_ENABLED=NO



WEBKITBROWSER_EXTRA_FLAGS = \
	-DCMAKE_CXX_FLAGS="-O3 $(TARGET_CXXFLAGS) -O2  -I$(STAGING_DIR)/usr/include/wdmp-c  -I$(STAGING_DIR)/usr/include/rdk/iarmbus  -I$(STAGING_DIR)/usr/include/trower-base64 -std=c++11 -fexceptions  -fexceptions -Wno-cast-align"  \
	-DCOMPILE_FLAGS="-std=c++11 -fexceptions -fexceptions -Wno-cast-align"

WEBKITBROWSER_PLUGIN_CONF_OPTS  +=   \
	$(WEBKITBROWSER_EXTRA_FLAGS)

$(eval $(cmake-package))
