amlogic_usb2_phy.ko
amlogic_usb3_v2_phy.ko
amlogic_usb2_c2_phy.ko
amlogic_usb_cc.ko
amlogic_usb3_c2_phy.ko
amlogic_usb_otg.ko
amlogic_usb_bc.ko
amlogic_usb_crg.ko
xhci-plat-hcd.ko
dwc3.ko
dwc3-of-simple.ko
dwc_otg.ko
amlogic-jtag.ko
amlogic-reg.ko
amlogic-ddr-tool.ko
amlogic-irblaster.ko
amlogic-reboot.ko
amlogic-hifidsp.ko
amlogic-crypto-dma.ko
amlogic-snd-soc.ko
amlogic-snd-codec-t9015.ko
amlogic-snd-codec-a1.ko
amlogic-snd-codec-tlv320adc3101.ko
amlogic-snd-codec-ad82584f.ko
amlogic_audiodsp.ko
amlogic_audioattrs.ko
amlogic_audiodata.ko
amlogic-snd-codec-dummy.ko


#amlogic_audiodsp.ko
#amlogic_audioattrs.ko
#amlogic_audiodata.ko
#amlogic-snd-codec-dummy.ko
