#!/bin/sh

start() {
  . /etc/datamount
  . /etc/overlaymount

  mount | grep /dev/system | grep ext4
  if [ $? -eq 0 ]
  then
    current_system=ext4
  else
    mount | grep /dev/system | grep erofs
    if [ $? -eq 0 ] ;then
      current_system=ero
    else
      mount | grep /dev/system | grep squashfs
      if [ $? -eq 0 ] ;then
        current_system=squashfs
      else
        current_system=ubi
      fi
    fi
  fi

  case ${current_system} in
    "ext4")
      data_ext4_handle
      ;;
    "ero")
      data_ext4_handle
      ;;
    "squashfs")
      data_ext4_handle
      ;;
    "ubi")
      data_ubi_handle
      ;;
    *)
      exit 1
      ;;
  esac

  do_overlay_mount /data/overlay
}

case "$1" in
  start)
    start
    ;;
  stop)
    ;;
  restart)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

