#!/bin/sh

#
# Copyright (c) 2022 Amlogic, Inc. All rights reserved.
# This source code is subject to the terms and conditions defined
# in the file 'LICENSE' which is part of this source code package.
# Description: S38 auto_shutdown file
#
# Starts the auto_shutdown daemon.
#
name=auto_shutdown
daemon=/usr/bin/$name
#time limit: 5 ~ 90 min
time=45

case "$1" in
    start|"")
        echo "Starting $name: "
        if [ -f "$daemon" ]; then
            $daemon $time &
        fi
        ;;
    stop)
        echo "Stopping $name: "
        pid=`ps | grep $name | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]; then
            kill $pid
        fi
        ;;
    *)
        echo "Usage: S38auto_shutdown {start|stop}" >&2
        exit 1
        ;;
esac
