################################################################################
#
# wpeframework-rdkservices
#
################################################################################

RDKSERVICES_VERSION = b660fdfe726aa097133fd48fe651d5a4410aff4a
RDKSERVICES_SITE_METHOD = git
RDKSERVICES_SITE = git://github.com/rdkcentral/rdkservices.git
#WPEFRAMEWORK_RDKSERVICES_INSTALL_STAGING = YES
#RDKSERVICES_DEPENDENCIES = wpeframework devicesettings iarmmgrs trower-base64
RDKSERVICES_DEPENDENCIES = wpeframework
RDKSERVICES_OPKG_NAME = "rdkservices"
RDKSERVICES_OPKG_VERSION = "1.0.0"
RDKSERVICES_OPKG_ARCHITECTURE = "${BR2_ARCH}"
RDKSERVICES_OPKG_MAINTAINER = "Metrological"
RDKSERVICES_OPKG_DESCRIPTION = "WPEFramework rdkservices"



RDKSERVICES_EXTRA_FLAGS = \
	-DCMAKE_CXX_FLAGS="-O3 $(TARGET_CXXFLAGS) -O2  -I$(STAGING_DIR)/usr/include/wdmp-c  -I$(STAGING_DIR)/usr/include/rdk/iarmbus  -I$(STAGING_DIR)/usr/include/trower-base64 -std=c++11 -fexceptions  -fexceptions -Wno-cast-align"  \
	-DCOMPILE_FLAGS="-std=c++11 -fexceptions -fexceptions -Wno-cast-align" \
	-DCMAKE_CXX_DEFINES=" $(TARGET_CXXDEFINES)  -fexceptions"

RDKSERVICES_CONF_OPTS = -DCMAKE_VERBOSE_MAKEFILE=1  \
		-DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 \
		$(RDKSERVICES_EXTRA_FLAGS)



WPE_COMPOSITOR ?= "compositor"
WPE_COMPOSITOR_IMPL ?= "Wayland"
WPE_COMPOSITOR_DEP ?= "westeros"
WPE_COMPOSITOR_EXTRAFLAGS ?= ""
WPE_COMPOSITOR_HARDWARE_READY ?= "0"

# ----------------------------------------------------------------------------

RDKSERVICES_CONF_OPTS +=   =  \
    -DPLUGIN_COMPOSITOR=ON \
    -DPLUGIN_COMPOSITOR_HARDWAREREADY=$(WPE_COMPOSITOR_HARDWARE_READY) \
    -DPLUGIN_COMPOSITOR_IMPLEMENTATION=$(WPE_COMPOSITOR_IMPL) \
    -DPLUGIN_COMPOSITOR_VIRTUALINPUT=ON $(WPE_COMPOSITOR_EXTRAFLAGS) \
    -DPLUGIN_COMPOSITOR=OFF,$(WPE_COMPOSITOR_DEP)



RDKSERVICES_CONF_OPTS +=  \
    -DBUILD_LLAMA=OFF \
    -DBUILD_AMLOGIC=OFF \
    -DPLUGIN_RDKSHELL=ON \
    -DSECAPI_LIB=OFF \
    -DCONTINUEWATCHING_DISABLE_SECAPI=OFF \
    -DPLUGIN_REMOTEACTIONMAPPING=OFF \
    -DPLUGIN_CONTROLSERVICE=OFF \
    -DPLUGIN_VREXMANAGER=OFF \
    -DENABLE_SECURITY_AGENT=ON \
    -DHAS_API_HDMI_CEC=OFF \
    -DENABLE_OPEN_CDMI=ON \
   -DPLUGIN_OPENCDMI_AUTOSTART=false \
   -DPLUGIN_OPENCDMI_OOP=OFF   \
   -DPLUGIN_DISPLAYSETTINGS=OFF \
    -DWAREHOUSE_API=OFF \
    -DBUILD_ENABLE_HDCP=OFF \
    -DHAS_API_HDMI_INPUT=OFF -DUSE_DS=NO  -DCLOCK_BRIGHTNESS_ENABLED=NO \
    -DHAS_API_DEVICEDIAGNOSTICS=OFF -DHAS_ACTIVITY_MONITOR=OFF -DHAS_API_FRAME_RATE=OFF \
    -DPLUGIN_LOGGING_PREFERENCES=OFF -DPLUGIN_USER_PREFERENCES=OFF -DPLUGIN_DATA_CAPTURE=OFF \
    -DENABLE_HDCP_PROFILE=OFF -DHAS_STATE_OBSERVER=OFF

RDKSERVICES_CXXFLAGS = "$(TARGET_CXXFLAGS) -fexceptions -xkd"


#RDKSERVICES_SUPPORTS_IN_SOURCE_BUILD = NO




WEBKITBROWSER_AUTOSTART ?= "false"
WEBKITBROWSER_MEDIADISKCACHE ?= "false"
WEBKITBROWSER_MEMORYPRESSURE ?= "databaseprocess:50m,networkprocess:100m,webprocess:300m,rpcprocess:50m"
WEBKITBROWSER_MEMORYPROFILE ?= "128m"
WEBKITBROWSER_MSEBUFFERS ?= "audio:2m,video:15m,text:1m"
WEBKITBROWSER_STARTURL ?= "http://localhost:8080/index.html"
WEBKITBROWSER_USERAGENT ?= "Mozilla/5.0 (Macintosh, Intel Mac OS X 10_11_4) AppleWebKit/602.1.28+ (KHTML, like Gecko) Version/9.1 Safari/601.5.17"
WEBKITBROWSER_DISKCACHE ?= "0"
WEBKITBROWSER_XHRCACHE ?= "false"
WEBKITBROWSER_TRANSPARENT ?= "false"
WEBKITBROWSER_THREADEDPAINTING ?= "1"

# ----------------------------------------------------------------------------

RDKSERVICES_CONF_OPTS  += -DPLUGIN_WEBKITBROWSER_UX=ON,-DPLUGIN_WEBKITBROWSER_UX=ON,

RDKSERVICES_CONF_OPTS  +=   -DPLUGIN_WEBKITBROWSER=ON \
   -DPLUGIN_WEBKITBROWSER_AUTOSTART=$(WEBKITBROWSER_AUTOSTART) \
   -DPLUGIN_WEBKITBROWSER_MEDIADISKCACHE=$(WEBKITBROWSER_MEDIADISKCACHE) \
   -DPLUGIN_WEBKITBROWSER_MEMORYPRESSURE=$(WEBKITBROWSER_MEMORYPRESSURE) \
   -DPLUGIN_WEBKITBROWSER_MEMORYPROFILE=$(WEBKITBROWSER_MEMORYPROFILE) \
   -DPLUGIN_WEBKITBROWSER_MSEBUFFERS=$(WEBKITBROWSER_MSEBUFFERS) \
   -DPLUGIN_WEBKITBROWSER_STARTURL=$(WEBKITBROWSER_STARTURL) \
   -DPLUGIN_WEBKITBROWSER_USERAGENT=$(WEBKITBROWSER_USERAGENT) \
   -DPLUGIN_WEBKITBROWSER_DISKCACHE=$(WEBKITBROWSER_DISKCACHE) \
   -DPLUGIN_WEBKITBROWSER_XHRCACHE=$(WEBKITBROWSER_XHRCACHE) \
   -DPLUGIN_WEBKITBROWSER_TRANSPARENT=$(WEBKITBROWSER_TRANSPARENT) \
   -DPLUGIN_WEBKITBROWSER_THREADEDPAINTING=$(WEBKITBROWSER_THREADEDPAINTING)



RDKSERVICES_CONF_OPTS  +=   \
	-DHAS_API_CONTINUE_WATCHING=OFF \
	-DHAS_FRONT_PANEL=OFF \
	-DPLUGIN_SYSTEMSERVICES=OFF \
	-DPLUGIN_SYSTEMSERVICES=OFF \
	-DHAS_TIMER=OFF \
	-DUSE_DS=OFF

RDKSERVICES_CONF_OPTS  +=   \
	-DPLUGIN_OPENCDMI_WIDEVINE=ON,,,wpeframework-ocdm-widevine \
	-DPLUGIN_OPENCDMI_PLAYREADY=ON,,,wpeframework-ocdm-playready \
	-DPLUGIN_OPENCDMI=ON \
	-DPLUGIN_OPENCDMI_AUTOSTART=true \
	-DPLUGIN_OPENCDMI_OOP=true

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_LOCATIONSYNC),y)
	WPEFRAMEWORK_LOCATIONSYNC_URI ?= "http://jsonip.metrological.com/?maf=true"
	RDKSERVICES_CONF_OPTS  +=  \
	-DPLUGIN_LOCATIONSYNC=ON  -DPLUGIN_LOCATIONSYNC_URI=$(WPEFRAMEWORK_LOCATIONSYNC_URI)
endif

#RDKSERVICES_SUBDIR=build


$(eval $(cmake-package))
