#!/bin/sh
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
export LD_PRELOAD=/usr/lib/libwesteros_gl.so.0.0.0
export XDG_RUNTIME_DIR="/run"

waitfordir=60
while [ ! -d $XDG_RUNTIME_DIR -a $waitfordir -gt 0 ];
do
    sleep 1
    echo "waiting XDG_RUNTIME_DIR mount while $waitfordir > 0 "
    waitfordir=$((waitfordir-1))
done
    echo 'XDG_RUNTIME_DIR mounted' 

if test -z "$WAYLAND_DISPLAY"; then
    export WAYLAND_DISPLAY=wayland-0
fi

#Dispmanx renderer support in RPI

if [ -f /usr/lib/libwesteros_render_dispmanx.so.0 ]; then
    RENDERER="/usr/lib/libwesteros_render_dispmanx.so.0 --enableCursor"
else
    RENDERER="/usr/lib/libwesteros_render_gl.so.0"
fi

if [ -f "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" ]; then
    echo "ERROR: A Wayland compositor $WAYLAND_DISPLAY is already running"
    exit 1
fi
#export WESTEROS_GL_DEBUG=3
export WESTEROS_GL_USE_BEST_MODE=1
export WESTEROS_GL_MAX_MODE=3840x2160
export WESTEROS_GL_GRAPHICS_MAX_SIZE=1920x1080
export WESTEROS_GL_USE_AMLOGIC_AVSYNC=1
export WESTEROS_SINK_AMLOGIC_USE_DMABUF=1
export WESTEROS_SINK_USE_FREERUN=1
export WESTEROS_GL_USE_REFRESH_LOCK=1
export WESTEROS_GL_USE_UEVENT_HOTPLUG=1

#For wesetros-sink
echo 1 > /sys/module/amvdec_ports/parameters/multiplanar
echo 1 > /sys/module/amvdec_ports/parameters/vp9_need_prefix
echo 1 > /sys/module/amvdec_ports/parameters/av1_need_prefix
echo 0 > /sys/module/drm/parameters/vblankoffdelay
echo 4181938 > /sys/module/amvdec_mh264/parameters/error_proc_policy

exec /usr/bin/westeros --renderer $RENDERER --display $WAYLAND_DISPLAY --window-size 1920x1080
#exec /usr/bin/westeros --renderer libwesteros_render_embedded.so.0.0.0 --display wayland-0 --window-size 1920x1080 --embedded --animate

