RDKCOBALT_VERSION = $(call qstrip,$(BR2_PACKAGE_RDKCOBALT_VERSION))
RDKCOBALT_PLUGIN_VERSION = $(shell echo $(RDKCOBALT_VERSION) | cut -d'.' -f1)

RDKCOBALT_PLUGIN_SITE_METHOD = local
RDKCOBALT_PLUGIN_SITE = $(TOPDIR)/../vendor/amlogic/cobalt/rdkcobalt-$(RDKCOBALT_PLUGIN_VERSION)
RDKCOBALT_PLUGIN_SUBDIR = plugin
RDKCOBALT_PLUGIN_CONF_OPTS = -DCMAKE_INSTALL_PREFIX:PATH=/usr \
  -DCMAKE_INSTALL_BINDIR:PATH=bin \
  -DCMAKE_INSTALL_SBINDIR:PATH=sbin \
  -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec \
  -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
  -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com \
  -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var \
  -DCMAKE_INSTALL_LIBDIR:PATH=lib \
  -DCMAKE_INSTALL_INCLUDEDIR:PATH=include \
  -DCMAKE_INSTALL_DATAROOTDIR:PATH=share \
  -DCMAKE_INSTALL_SO_NO_EXE=0 \
  -DCMAKE_VERBOSE_MAKEFILE=1 \
  -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DPLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE=starboard/rdk/arm/configuration_public.h \
  -DPLUGIN_COBALT_CLIENTIDENTIFIER=wst-cobalt \
  -DCXX_INCLUDES=-I$(RDKCOBALT_PLUGIN_DIR)/git/src \
  -Wno-dev

# for htmlapp base on Cobalt
ifeq ($(BR2_PACKAGE_RDKCOBALT_HTMLAPP),y)
  RDKCOBALT_PLUGIN_CONF_OPTS += -DPLUGIN_COBALT_HTMLAPP=ON \
                                -DPLUGIN_HTMLAPP_CLIENTIDENTIFIER=wst-chtmlapp \
                                -DPLUGIN_HTMLAPP_WEBFILEPATH=$(BR2_PACKAGE_RDKCOBALT_HTMLAPP_WEBFILEPATH) \
                                -DPLUGIN_HTMLAPP_URL=$(BR2_PACKAGE_RDKCOBALT_HTMLAPP_URL)
  endif

RDKCOBALT_PLUGIN_INSTALL_STAGING = YES
RDKCOBALT_PLUGIN_DEPENDENCIES = rdkcobalt

RDKCOBALT_PLUGIN_DEPOT_TOOLS_PATH = $(RDKCOBALT_PLUGIN_DIR)depot_tools
RDKCOBALT_PLUGIN_STARBOARD_PATH = $(RDKCOBALT_PLUGIN_DIR)/starboard

$(eval $(cmake-package))
